In [29]:
import os

In [30]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

import warnings
warnings.filterwarnings('ignore')

#**Load Dataset**
---

In [ ]:
# Load the datasets
train_df = pd.read_csv('../data/experiments/raw/train.csv')

In [32]:
train_df['Date'] = pd.to_datetime(train_df['Date'])
train_df = train_df.sort_values(['Date','Store_id'])

In [33]:
train_df.agg(min_date=('Date', 'min'), max_date=('Date', 'max')).reset_index()

,index,Date
0,min_date,2018-01-01
1,max_date,2019-05-31


In [34]:
train_df['Date'].nunique()

516

In [35]:
train_df['Store_id'].nunique()

365

In [36]:
unique_counts = train_df.groupby('Store_id').agg(unique_counts=('Date', 'nunique'))
unique_counts[unique_counts['unique_counts'] !=516]

,unique_counts
Store_id,


In [37]:
unique_counts = train_df.groupby('Store_id').agg(unique_counts=('Store_Type', 'nunique'))
unique_counts[unique_counts['unique_counts'] !=1]

,unique_counts
Store_id,


In [38]:
unique_counts = train_df.groupby('Store_id').agg(unique_counts=('Location_Type', 'nunique'))
unique_counts[unique_counts['unique_counts'] !=1]

,unique_counts
Store_id,


In [39]:
unique_counts = train_df.groupby('Store_id').agg(unique_counts=('Region_Code', 'nunique'))
unique_counts[unique_counts['unique_counts'] !=1]

,unique_counts
Store_id,


In [40]:
unique_counts = train_df.groupby('Date').agg(unique_counts=('Holiday', 'nunique'))
unique_counts[unique_counts['unique_counts'] !=1]

,unique_counts
Date,


In [41]:
unique_counts = train_df.groupby([ 'Date','Region_Code','Location_Type','Store_Type']).agg(unique_counts=('Discount', 'nunique'))
unique_counts[unique_counts['unique_counts'] >1]

unique_counts
Date       Region_Code Location_Type Store_Type               
2018-01-04 R4          L2            S4                      2
2018-01-05 R4          L2            S4                      2
2018-01-11 R4          L2            S4                      2
2018-01-12 R4          L2            S4                      2
2018-01-13 R1          L1            S4                      2
...                                                        ...
2019-05-31 R3          L1            S3                      2
                       L2            S3                      2
                                     S4                      2
                       L3            S1                      2
           R4          L2            S3                      2

[9074 rows x 1 columns]

**Observations:**
* **Dataset Scale**: Contains 516 daily observations across 365 unique stores.
* **Data Integrity**: Store attributes (Type, Location, and Region Code) are consistent across all records, indicating high data quality.
* **Operational Synchrony**: Holiday schedules are uniform across the entire store network.
* **Promotion Strategy**: Discounts are non-uniform and managed at the individual store level, suggesting a localized pricing strategy.

#**Split Data**
---

In [ ]:
test_df=train_df[train_df['Date'] >= '2019-05-01']
val_df=train_df[(train_df['Date'] >= '2019-02-01') & (train_df['Date'] < '2019-05-01')]
train_df=train_df[train_df['Date'] < '2019-02-01']


In [ ]:
train_df.to_csv('../data/experiments/train/train_data.csv', header=True, index=False)
val_df.to_csv('../data/experiments/validate/validate_data.csv', header=True, index=False)
test_df.to_csv('../data/experiments/test/test_data.csv', header=True, index=False)